Problem - 1: Array Creation:

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty Array (2x2):")
print(empty_array, "\n")

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("2. All-Ones Array (4x2):")
print(ones_array, "\n")

# 3. Return a new array of given shape and type, filled with fill value
fill_value_array = np.full((3, 3), 7)  # Example: 3x3 array filled with 7
print("3. Array Filled with Value 7 (3x3):")
print(fill_value_array, "\n")

# 4. Return a new array of zeros with the same shape and type as a given array
reference_array = np.array([[5, 6], [7, 8]])
zeros_like_array = np.zeros_like(reference_array)
print("4. Zeros Array with Same Shape as Reference Array:")
print(zeros_like_array, "\n")

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
print("5. Ones Array with Same Shape as Reference Array:")
print(ones_like_array, "\n")

# 6. Convert a list to a NumPy array
new_list = [1, 2, 3, 4]
converted_array = np.array(new_list)
print("6. Converted List to NumPy Array:")
print(converted_array)


1. Empty Array (2x2):
[[4.90909656e-310 0.00000000e+000]
 [6.90437819e-310 6.90439266e-310]] 

2. All-Ones Array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

3. Array Filled with Value 7 (3x3):
[[7 7 7]
 [7 7 7]
 [7 7 7]] 

4. Zeros Array with Same Shape as Reference Array:
[[0 0]
 [0 0]] 

5. Ones Array with Same Shape as Reference Array:
[[1 1]
 [1 1]] 

6. Converted List to NumPy Array:
[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_range = np.arange(10, 50)
print("1. Array with values ranging from 10 to 49:")
print(array_range, "\n")

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("2. 3x3 Matrix with values ranging from 0 to 8:")
print(matrix_3x3, "\n")

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3. 3x3 Identity Matrix:")
print(identity_matrix, "\n")

# 4. Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print("4. Random Array of size 30 and its Mean:")
print("Random Array:", random_array)
print("Mean:", mean_value, "\n")

# 5. Create a 10x10 array with random values and find the min and max values
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("5. 10x10 Random Array with Min and Max Values:")
print("Minimum Value:", min_value)
print("Maximum Value:", max_value, "\n")

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Replace 5th element (index 4 in 0-based indexing)
print("6. Zero Array with 5th Element Replaced by 1:")
print(zero_array, "\n")

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = [1, 2, 0, 0, 4, 0]
reversed_array = np.array(arr)[::-1]
print("7. Reversed Array:")
print(reversed_array, "\n")

# 8. Create a 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("8. 2D Array with 1 on Border and 0 Inside:")
print(border_array, "\n")

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Fill alternate cells in odd rows
checkerboard[::2, 1::2] = 1  # Fill alternate cells in even rows
print("9. 8x8 Checkerboard Pattern Matrix:")
print(checkerboard)


1. Array with values ranging from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

2. 3x3 Matrix with values ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]] 

3. 3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

4. Random Array of size 30 and its Mean:
Random Array: [0.16890329 0.5436912  0.85200688 0.96990006 0.22800787 0.40090309
 0.63794497 0.00185963 0.74659896 0.48872068 0.80872852 0.15830822
 0.53577626 0.23048631 0.6079232  0.68999956 0.50380907 0.3494573
 0.5511391  0.40009182 0.27140028 0.89905992 0.92830728 0.66729541
 0.01720075 0.40200669 0.85899944 0.16151651 0.06885728 0.3427549 ]
Mean: 0.4830551482837707 

5. 10x10 Random Array with Min and Max Values:
Minimum Value: 0.01504579127179273
Maximum Value: 0.9948414420015157 

6. Zero Array with 5th Element Replaced by 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] 

7. Reversed Array:
[0 4 0 0 2 1] 

8. 2D Array with 1 on Border and 0 Inside

Problem - 3: Array Operations:

In [1]:
import numpy as np

# Initialize arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
addition_result = x + y
print("1. Addition of x and y:")
print(addition_result, "\n")

# 2. Subtract the two arrays
subtraction_result = x - y
print("2. Subtraction of x and y:")
print(subtraction_result, "\n")

# 3. Multiply the array `x` with an integer (e.g., 2)
scalar_multiplication = x * 2
print("3. Multiplication of x with 2:")
print(scalar_multiplication, "\n")

# 4. Find the square of each element of the array `x`
squared_elements = np.square(x)
print("4. Square of each element in x:")
print(squared_elements, "\n")

# 5. Find the dot product
dot_product_vw = np.dot(v, w)
dot_product_xv = np.dot(x, v)
dot_product_xy = np.dot(x, y)
print("5. Dot Products:")
print(f"Dot product of v and w: {dot_product_vw}")
print(f"Dot product of x and v: {dot_product_xv}")
print(f"Dot product of x and y:\n{dot_product_xy}\n")

# 6. Concatenate x and y along rows, and v and w along columns
concat_xy_row = np.concatenate((x, y), axis=0)  # Along rows
concat_vw_col = np.vstack((v, w))  # Along columns
print("6. Concatenation Results:")
print("Concatenation of x and y along rows:")
print(concat_xy_row)
print("Concatenation of v and w along columns:")
print(concat_vw_col, "\n")


1. Addition of x and y:
[[ 6  8]
 [10 13]] 

2. Subtraction of x and y:
[[-4 -4]
 [-4 -3]] 

3. Multiplication of x with 2:
[[ 2  4]
 [ 6 10]] 

4. Square of each element in x:
[[ 1  4]
 [ 9 25]] 

5. Dot Products:
Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y:
[[19 22]
 [50 58]]

6. Concatenation Results:
Concatenation of x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
[[ 9 10]
 [11 12]] 

7. Error in Concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Explanation:
The error occurs because `x` is a 2x2 matrix while `v` is a 1D array with 2 elements.
To fix this, `v` must be reshaped to match the dimensions of `x` along the intended axis.


Problem - 4: Matrix Operations:

In [ ]:
import numpy as np

# Initialize matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A⁻¹ = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("1. Prove A.A⁻¹ = I:")
print("A * A⁻¹:")
print(identity_matrix)
print("Is A * A⁻¹ an Identity Matrix? ", np.allclose(identity_matrix, np.eye(2)), "\n")

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("2. Prove AB ≠ BA:")
print("AB:")
print(AB)
print("BA:")
print(BA)
print("Is AB equal to BA? ", np.array_equal(AB, BA), "\n")

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("3. Prove (AB)^T = B^T * A^T:")
print("(AB)^T:")
print(AB_T)
print("B^T * A^T:")
print(BT_AT)
print("Is (AB)^T equal to B^T * A^T? ", np.array_equal(AB_T, BT_AT), "\n")

# System of Linear Equations
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

# Represent the equations in matrix form AX = B
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])  # Coefficients of variables
B_eq = np.array([-1, -3, 9])  # Constants on the right-hand side

# Solve for X using inverse methods
A_inv_eq = np.linalg.inv(A_eq)
X_solution = np.dot(A_inv_eq, B_eq)

print("4. Solve System of Linear Equations Using Inverse Methods:")
print("Solution [x, y, z]:")
print(X_solution, "\n")

# Solve using np.linalg.solve (preferred method)
X_solution_solve = np.linalg.solve(A_eq, B_eq)
print("Solution Using np.linalg.solve:")
print(X_solution_solve)


1. Prove A.A⁻¹ = I:
A * A⁻¹:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is A * A⁻¹ an Identity Matrix?  True 

2. Prove AB ≠ BA:
AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
Is AB equal to BA?  False 

3. Prove (AB)^T = B^T * A^T:
(AB)^T:
[[23 51]
 [13 29]]
B^T * A^T:
[[23 51]
 [13 29]]
Is (AB)^T equal to B^T * A^T?  True 

4. Solve System of Linear Equations Using Inverse Methods:
Solution [x, y, z]:
[ 2.  1. -2.] 

Solution Using np.linalg.solve:
[ 2.  1. -2.]


Hello world


In [ ]:
)

1. Empty Array (2x2):
[[1.e-05 0.e+00]
 [0.e+00 1.e-05]] 



4. Zeros Array with Same Shape as Reference Array:
[[0 0]
 [0 0]] 

